- README.md
A few minor issues - most importantly, fixed the title of the readme. Also:
* Removed == and -- breakers (Markdown auto-renders these after a title)
* Small edits
> Fixed some issues in the main README file

- bsg_misc/bsg_dlatch.v
Addressing issues #38 and #21.
Adding the i_know_this_is_a_bad_idea_p parameter and warning. Changed en_i port to clk_i. Refactored to use always_latch rather than always_ff.
> Update to bsg_dlatch

- bsg_link/bsg_link_iddr_phy.v
- bsg_link/bsg_link_oddr_phy.v
Standalone DDR input and output PHY.
Schematic and more information: https://docs.google.com/document/d/1lmkOxvlAvxrk_MM5W8xv3ho2DS26xbOMTCqUIyS6di8/edit?ts=5cf76063#heading=h.o6ptt6mn49us
> Add bsg_link DDR PHY

- bsg_link/bsg_link_source_sync_downstream.v
- bsg_link/bsg_link_source_sync_upstream.v
This pair of modules are developed based on bsg_comm_link/bsg_source_sync_input and bsg_comm_link/bsg_source_sync_output.
> Add bsg_link source sync input / output

- bsg_noc/bsg_wormhole_router.v
Fixed everything except for parameter names... 
Changing parameter names can be painful, some BP designs need to be updated.
> Wormhole Router

- bsg_tag/bsg_tag_trace_replay.v
Used to enable or disable tag masters for multi-master systems.
> [bsg_tag_trace_replay] adding an output enable array

- bsg_misc/bsg_defines.v
- bsg_misc/bsg_dff_reset.v
- bsg_noc/bsg_wormhole_router.vh
- bsg_noc/bsg_wormhole_router_adapter.v
- bsg_noc/bsg_wormhole_router_adapter_in.v
- bsg_noc/bsg_wormhole_router_adapter_out.v
- bsg_noc/bsg_wormhole_router_generalized.v
and new wormhole header format
> Changing wormhole adapters to use SIPO/PISO

- bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
> Added missing parameter (unconnected) in hard/ultrascale_plus/bsg_mem_1rw_sync_mask_write_bit.v

- bsg_fpu/bsg_fpu_add_sub.v
- bsg_fpu/bsg_fpu_i2f.v
The FPGA warnings came back in the FPU unit. So... I took a hammer and fixed them again.
> Yet again, trying to fix the FPU warnings in FPGA compilation

- .gitmodules
> Removing vscale submodule

- bsg_test/bsg_nonsynth_ramulator_hbm.v
- testing/bsg_test/bsg_nonsynth_ramulator_hbm/hbm_trace_gen.py
- testing/bsg_test/bsg_nonsynth_ramulator_hbm/latency.py
- testing/bsg_test/bsg_nonsynth_ramulator_hbm/sv.include
- testing/bsg_test/bsg_nonsynth_ramulator_hbm/testbench.v
* adds a request trace in the hbm ramulator module
* expands testbench trace to test DRAM latency
> Small ramulator changes

- bsg_cache/bsg_cache_non_blocking_mhu.v
- bsg_dataflow/bsg_1_to_n_tagged_fifo_shared.v
This PR fixes some syntax errors.
> Fix syntax error

- bsg_test/bsg_dramsim3.cpp
- bsg_test/bsg_nonsynth_dramsim3_map.v
* fixes an address mapping bug
* cleanup an unused temporary (when no debugging) in C++ source
> Dramsim3 fix

- .gitmodules
- imports/Makefile
* fixes #223 
* adds a makefile for imports
> fixes DRAMSim3 submodule issue

- hard/saed_90/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
. wrapped bsg_clkgate_optional with an if statement
> modified for task6 of ee525 module2

- bsg_dataflow/bsg_parallel_in_serial_out.v
- hard/saed_90/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
in bsg_parallel_in_serial_out moving typedef enum out of the generate scope
> Ee525 module3 fix

- bsg_noc/bsg_wormhole_router.v
- bsg_noc/bsg_wormhole_router_output_control.v
> Change bsg_wormhole_router to rv& via output_control

- bsg_test/bsg_trace_replay.v
Simple code refactor addressing feedback in #264 from @tommydcjung.
> Merging case statements for code clarity

- bsg_test/bsg_trace_replay.v
Apologies for the trace-replay PR spams, I think this is it for the time being.
The finish_on_error_p parameter (defaults to 1 or true) basically asks if the simulation should terminate if an error is found (mismatch trace or unknown op code).
There is also a bug fix in here. When an unknown op was given, the instr_completed wire was not asserted, therefore trace replay never moved forward and the display saying an unknown op was found never displayed because that required instr_completed to be asserted so it would silently stall forever.
I also changed it so error_o goes high when an unknown op is found.
> Adding finish_on_error_p parameter.

- .gitmodules
> Switch to BSG External version of DRAMSim3

- bsg_test/bsg_nonsynth_test_rom.v
> Allowing readmemh or readmemb in test rom

- bsg_test/bsg_nonsynth_dpi_gpio.hpp
- bsg_test/bsg_nonsynth_dpi_gpio.v
We use this to enable/disable tracers from C/C++ in replicant.
> Created DPI GPIO module

- bsg_test/bsg_nonsynth_dpi.hpp
> Added missing cstring header

- bsg_test/bsg_nonsynth_dramsim3.v
The fake mask input to the DMA memory module was wrong in the #323.
> Fixed the fake mask in the unmasked mode DRAMSim3

- bsg_dataflow/bsg_parallel_in_serial_out_passthrough.v
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough/.gitignore
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough/Makefile
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough/sv.include
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough/testbench.v
Adding passthrough PISO and tests
> Passthrough PISO

- bsg_dataflow/bsg_serial_in_parallel_out_passthrough.v
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/.gitignore
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/Makefile
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/sv.include
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/testbench.v
Adding passthrough SIPO and test
> Adding passthrough sipo

- hard/free_45/bsg_mem/bsg_mem_1r1w_sync.v
- hard/free_45/bsg_mem/bsg_mem_1rw_sync.v
- hard/free_45/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
- hard/free_45/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
- hard/free_45/bsg_mem/bsg_mem_2r1w_sync.v
- hard/free_45/bsg_mem/bsg_mem_3r1w_sync.v
This PR adds hardened RAMs for the free45 technology. 
Note: Only BP-specific memories are included.
> Hardened free45 memories

- bsg_dataflow/bsg_parallel_in_serial_out_passthrough_dynamic.v
- bsg_dataflow/bsg_serial_in_parallel_out_passthrough_dynamic.v
Passthrough PISO and SIPO with dynamic length
> Add Dynamic Passthrough PISO and SIPO

- bsg_noc/bsg_mesh_router_decoder_dor.v
Compilation fails in Verilator.
> Remove unused format specifier

- bsg_misc/bsg_round_robin_arb.py
- bsg_misc/bsg_round_robin_arb.v
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough_arb/.gitignore
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough_arb/Makefile
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough_arb/sv.include
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough_arb/testbench.v
This adds a hold on valid mode to the round robin arbiter, where it will not switch its grant unless acked.
> Adding hold on valid to rr_arb

- bsg_test/bsg_dramsim3.cpp
- bsg_test/bsg_nonsynth_dramsim3.v
- testing/bsg_test/bsg_nonsynth_dramsim3/Makefile
- testing/bsg_test/bsg_nonsynth_dramsim3/hbm_trace_gen.py
- testing/bsg_test/bsg_nonsynth_dramsim3/testbench.v
- testing/bsg_test/bsg_nonsynth_dramsim3/testbench_multi.v
Adds support for multiple DRAMSim3 instantiations.
> Supports multiple instantiation of DRAMSim3 module

- bsg_tag/bsg_tag_client.v
> Enabling 1-bit bsg_tag_client

- bsg_misc/bsg_dff_reset_en_bypass.v
> Fixing disconnected reset_val_p in bsg_dff_reset_en_bypass

- bsg_test/bsg_nonsynth_axi_mem.v
Pulled from https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/testbenches/common/v/bsg_nonsynth_manycore_axi_mem.v
> Adding axi mem for testing

- bsg_cache/bsg_cache_to_test_dram.v
- bsg_dataflow/bsg_round_robin_n_to_1.v
> [bsg_cache_to_test_dram] replace round robin module

- bsg_cache/bsg_cache_to_dram_ctrl.v
- bsg_test/bsg_nonsynth_axi_mem.v
Should be uncontroversial fixes. Ran into these when bring up BP testbenches
> Minor changes to DRAM modules

- bsg_mem/bsg_cam_1r1w.v
- bsg_mem/bsg_cam_1r1w_replacement.v
- bsg_mem/bsg_cam_1r1w_sync_unmanaged.v
- bsg_mem/bsg_cam_1r1w_tag_array.v
- bsg_mem/bsg_cam_1r1w_unmanaged.v
- bsg_mem/bsg_mem_1r1w_one_hot.v
- bsg_misc/bsg_defines.v
- bsg_misc/bsg_mux_one_hot.v
> Support for 0/1 element CAM

- bsg_test/bsg_dramsim3_pkg.v
This is the configuration we validated on FPGA DRAMSim3 for BP
> Adding bsg_dramsim3_lpddr_2Gb_x16_pkg

- bsg_test/bsg_nonsynth_dpi_errno.hpp
- bsg_test/bsg_nonsynth_dpi_to_fifo.v
* Lower valid after posedge to avoid negedge assertions
* Add new errorno value
> DPI Fixes and additions

- bsg_test/bsg_nonsynth_axi_mem.v
Otherwise AXI_mem will accept requests during reset
> Adding reset states to axi_mem

- bsg_mem/bsg_mem_dma.cpp
- bsg_mem/bsg_mem_dma.hpp
- bsg_mem/bsg_nonsynth_mem_1r1w_sync_mask_write_byte_dma.v
- testing/bsg_mem/bsg_nonsynth_mem_1rw_sync_mask_write_byte_dma/Makefile
Switches to using raw pointer allocated with mmap.
> Bsg mem dma

- bsg_test/bsg_nonsynth_clock_gen.v
- bsg_test/bsg_nonsynth_dpi_clock_gen.v
> Adding dpi clock gen to ifdef in bsg_nonsynth_clk_gen

- bsg_misc/bsg_mul_add.v
- hard/ultrascale_plus/bsg_misc/bsg_mul_add.v
Not sure how to handle the ZYNQ variable -- any other better way?
> Variable pipeline depth mul_add for easy DSP absorption on FPGAs

- bsg_dataflow/bsg_fifo_1r1w_large.v
initials / assertions should not be present in synthesis
> Guarding initial from synthesis

- bsg_misc/bsg_counting_leading_zeros.v
Also, fix when input bits are all zeros.
> fix clz output width

- testing/bsg_cache/axe_test/Makefile
- testing/bsg_cache/dmc/Makefile
- testing/bsg_cache/lock_test/Makefile
- testing/bsg_cache/regression/Makefile
- testing/bsg_cache/regression_64/Makefile
- testing/bsg_cache/regression_v2/Makefile
Adding missing incdir to fix testbenches
> Adding bsg_cache include to testbenches

- bsg_misc/bsg_round_robin_arb.py
> Added support for python3

- bsg_misc/bsg_counter_clear_up.v
Making it so that synthesis tool can clock-gate bsg_counter_clear_up
> bsg_counter_clear_up clk gating

- bsg_cache/bsg_cache_dma_to_wormhole.v
- bsg_cache/bsg_wormhole_to_cache_dma_fanout.v
> Adding synopsys pragma to bsg_cache_dma_to_wormhole

- bsg_mem/bsg_mem_1r1w_sync.v
- bsg_mem/bsg_mem_1r1w_sync_banked.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_bit_synth.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_byte.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_byte_synth.v
- bsg_mem/bsg_mem_1r1w_sync_synth.v
- hard/common/bsg_mem/bsg_mem_generator.py
- Banked 1r1w
- 1r1w latch last read behavior
- 1r1w byte mask
> 1r1w enhancements

- bsg_test/bsg_dramsim3_pkg.v
* adds a dual channel hbm2 chip
> HBM2 2Gb chip

- hard/tsmc_28/bsg_misc/bsg_buf.v
- hard/tsmc_28/bsg_misc/bsg_dff.v
- hard/tsmc_28/bsg_misc/bsg_mux.v
- hard/tsmc_28/bsg_misc/bsg_nand.v
- hard/tsmc_28/bsg_misc/bsg_nor3.v
- hard/tsmc_28/bsg_misc/bsg_xnor.v
This PR adds miscellaneous TSMC28 hardened modules, specifically those used in bsg_strobe
> Adding misc tsmc28 hard

- hard/tsmc_28/bsg_link/bsg_link_isdr_phy.v
- hard/tsmc_28/bsg_link/bsg_link_osdr_phy.v
- hard/tsmc_28/bsg_link/tcl/bsg_link_sdr.constraints.tcl
Adding hardened TSMC28 bsg_link
> Adding bsg_link 28

- bsg_dmc/bsg_dmc.v
Adding comments in bsg_dmc.v for PCB routing guidelines
> Dmc LPDDR Routing Guidelines

- bsg_misc/bsg_sparse_to_dense_boolean.v
> Add missing commas in bsg_sparse_to_dense_boolean.v

- bsg_riscv/bsg_htif/bsg_fsb_to_htif_connector.v
Hi there!
This code was not compliant Verilog.
> Fix uncompliant assignment

- hard/ultrascale_plus/bsg_misc/bsg_mux.v
Tested with 2/3/4:1 muxes with balanced_p and harden_p -- each synthesizes, FPGA-simulates.
> Clock Mux macro for Ultrascale

- hard/ultrascale_plus/bsg_misc/bsg_clkgate_optional.v
- hard/ultrascale_plus/bsg_misc/bsg_mux.v
+ fixes for bsg_mux (argument reordering)
> Clock gate hard macro for Xilinx Ultrascale

- bsg_cache/bsg_cache.v
- testing/bsg_cache/common/basic_checker_32.v
- testing/bsg_cache/regression/testbench.v
- testing/bsg_cache/regression_64/Makefile
- testing/bsg_cache/regression_64/basic_checker.v
- testing/bsg_cache/regression_64/testbench.v
- testing/bsg_cache/regression_v2/testbench.v
Fixing the input handshaking interface.
> [bsg_cache] ready_o -> yumi_o

- testing/bsg_noc/bsg_barrier/Makefile
- testing/bsg_noc/bsg_mesh_router/Makefile
- testing/bsg_noc/bsg_mesh_router/test_bsg.v
- testing/bsg_noc/bsg_mesh_to_ring_stitch/Makefile
- testing/bsg_noc/bsg_wormhole_network/Makefile
- testing/bsg_noc/bsg_wormhole_router_adapter_in/testbench.v
- testing/bsg_noc/bsg_wormhole_router_adapter_out/Makefile
- testing/bsg_noc/bsg_wormhole_router_adapter_out/testbench.v
Updates testbenches for bsg_noc to run properly. bsg_wormhole_router_adapter_out test fails for unknown but likely unrelated reason.
> Bsg noc testbench update

- testing/bsg_tag/Makefile
- testing/bsg_tag/test_bsg.v
Updates the testbench and makefile for bsg_tag to allow for compilation, refactors using Makefile.sim
> Fixes testbench for bsg_tag

- testing/bsg_fpu/bsg_fpu_sticky/Makefile
Fixes environment variables and vcs command for bsg_fpu_sticky's test makefile
> Fpu testbench fix

- hard/ultrascale_plus/bsg_link/README.md
- hard/ultrascale_plus/bsg_link/bsg_link_ddr_upstream.v
- hard/ultrascale_plus/bsg_link/bsg_link_iddr_phy.v
- hard/ultrascale_plus/bsg_link/bsg_link_oddr_phy.v
- hard/ultrascale_plus/bsg_link/tcl/bsg_link_ddr.sample_constraints.tcl
- hard/ultrascale_plus/bsg_link/tcl/bsg_link_ddr.sample_constraints.xdc
- hard/ultrascale_plus/bsg_link/tcl/example_placement_constraints.xdc
Contains Ultrascale Plus source codes and XDC constraints, and README.
> bsg_link FPGA implementation release

- hard/common/bsg_mem/bsg_mem_generator.py
python2->python2/3 compatibility
> Use integer division in bsg_mem_generator.py

- hard/ultrascale_plus/bsg_mem/bsg_mem_1r1w_sync_mask_write_byte.sv
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
This PR fixes include paths unchanged from #666
> Hotfix: verilog includes

- bsg_noc/bsg_wormhole_router_packet_parser.sv
> Adding missing BSG_ABSTRACT_MODULE
