bespoke-silicon-group/basejump_stl

- bsg_noc/bsg_noc_pkg.v
No functional change, but if you leave enum values unsized, it causes issues in concatenations involving them
> Adding explicit widths to NOC direction for Verilator compatibility

- bsg_noc/bsg_wormhole_router.v
- bsg_noc/bsg_wormhole_router_adapter_in.v
- bsg_noc/bsg_wormhole_router_adapter_out.v
- testing/bsg_noc/bsg_wormhole_router_adapter_in/Makefile
- testing/bsg_noc/bsg_wormhole_router_adapter_in/sv.include
- testing/bsg_noc/bsg_wormhole_router_adapter_in/testbench.v
- testing/bsg_noc/bsg_wormhole_router_adapter_out/Makefile
- testing/bsg_noc/bsg_wormhole_router_adapter_out/testbench.v
This PR changes the wormhole_router and _adapters to use bsg_noc links on the network side. The testbenches have been updated to work with the new interface and I've tested the whole system with new links on BlackParrot in a separate branch there.
> Changing wormhole router to use bsg_noc_links instead of ready-valid

- bsg_dataflow/bsg_flow_counter.v
This change sets the max_step_p parameter to have a value of 1 for bsg_counter_up_down inside bsg_flow_counter. This eliminates a width mismatch warning from VCS and DC.
The bsg_flow_counter only ever increments or decrements by 1 since it is used to count tokens or credits of a single module between a r&v and valid-yumi input/output pair.
> set default max_step_p of bsg_counter_up_down in bsg_flow_counter to 1

- bsg_misc/bsg_defines.v
BSG_CDIV does integer division between the two inputs but ceils the value rather than floor like traditional integer division.
> Adding BSG_CDIV to bsg_defines.v

- bsg_noc/bsg_noc_links.vh
This definition is a little bit tricky:
1. wormhole_packet_width: Given a payload data packet, what is the minimum bits needed for the full wormhole packet (including both header and payload). 
2. wormhole_packet_s: Given a pre-calculated full packet width (which is multiple of wormhole channel width), define the wormhole packet struct.
> Wormhole Packet Definition

- bsg_link/bsg_link_ddr_downstream.v
- bsg_link/bsg_link_ddr_upstream.v
During simulation, this assertion is falsely triggered because initial value of reset_i, v_0 and v_1 are all X... Do not assert when reset signal is X or Z, when v_0 and v_1 is X, Z or both zero.
> Use extra data bit in bsg link ddr

- bsg_misc/bsg_defines.v
- bsg_misc/bsg_unconcentrate_static.v
'z will get synthesized into tri-state (not disconnect as it is intended here). Therefore, I surrounded the 'z assigns in translate off/on pragmas so that DC simply leaves them disconnected.
> Hotfix BSG Unconcentrate Static for Synthesis

- bsg_noc/bsg_mesh_router.v
Use asserts instead of ifs.  Asserts can be disabled by tools, but if () finishes cannot.  Standard use for Verilator is to disable asserts until reset sequence is over, then re-enable them.  Otherwise, the asserts will fire and terminate during reset sequence (which can extend before or after when reset_i itself is low)
> Changing if-errors to assert-else-errors in mesh_router

- bsg_dataflow/bsg_fifo_1r1w_pseudo_large.v
Many group members asked me why channel_tunnel prints out "fifo is overflowing" during simulation. Should not print this out when verbose_p==0!
> Pseudo large fifo: only verbose when verbose_p==1

- bsg_fpu/bsg_fpu_add_sub.v
- bsg_fpu/bsg_fpu_i2f.v
These added attributes solve warnings in the Xilinx tool chain related to: 
* Unused registers (Trimmed)
* Resource Sharing
The latter prevents a timing loop from being inferred in the toolchain, or at
least prevents the messages from occurring.
This is preliminary. We don't have a failure case (yet), but we do have the warnings.
> Added XILINX attributes to eliminate FPU timing loops/warnings

- bsg_mem/bsg_mem_1r1w.v
- bsg_mem/bsg_mem_2r1w.v
- bsg_mem/bsg_mem_3r1w.v
#144 #145 #146 
I was unable to parse this part of the style guide
>Purely logical operators for purely non-bitvector inputs. Here you have a bunch of word values that you that you are trying to combine together, C-style into logical boolean expressions. The expression will have a bunch of numerical values that you are testing for equality, less than, greater than, or zero/non-zeroness. You can not have any of the inputs to the expression be bitvector values.  In this case, it is permissible to use logical boolean operators (i.e. &&, ||, if, !), but you should not use any bitwise operators (i.e., &, |, ^), especially the bitwise ~ operator. This is consistent with C usage.
Is using w_v_i and r_v_i in mixed logical expressions permitted? w_v_i == 1'b1 seems verbose
> Converting bsg_mem_xr1w.v assertions to pure logical expressions

- bsg_cache/bsg_cache.v
- bsg_cache/bsg_cache_dma.v
- testing/bsg_cache/common/bsg_nonsynth_dma_model.v
The bug is that when the DMA engine evicts a block, it reads a word and wait for the read word to be accepted by the evict FIFO, before it reads the next word. If the evict FIFO is not ready, and the incoming load takes the empty spot in TL stage (reading tag/data_mem), it disturbs the output of the data_mem, before it is accepted by the evict FIFO. This bug went undetected, because in the previous test setup, the evict FIFO was always able to drain without getting stalled. It was discovered when I added delays between receiving the dma_request and starting accepting/sending main memory data in bsg_nonsynth_dma_model.
The fix is to block the incoming requests when the eviction is in progress. I added a signal dma_evict_o to DMA engine which says the eviction is in progress.
> fix the bug with dma evict data read disrupted by incoming load

- bsg_misc/bsg_lru_pseudo_tree_encode.v
- testing/bsg_misc/bsg_lru_pseudo_tree_encode/Makefile
- testing/bsg_misc/bsg_lru_pseudo_tree_encode/sv.include
- testing/bsg_misc/bsg_lru_pseudo_tree_encode/testbench.v
Good evening,
Here is the basic idea. the efficient implementation only needs 4 of 2-to-1 muxes at most.
the current implementation causes huge critical path in the cache design.
> efficient implementation of lru_encode

- bsg_cache/bsg_cache_to_dram_ctrl.v
- testing/bsg_cache/dmc/sv.include
- testing/bsg_cache/dmc/testbench.v
Currently we append cache_id to top bits of dram-request-address, then different caches are mapped to different dram banks, so that cmds from multiple caches can be processed in parallel.
However, we may want to support DRAM of different sizes. In this pull request, cache_id bits can be inserted to multiple places, based on new input port dram_size_i. It supports all possible DRAM sizes that can be purchased from Digikey (256Mb, 512Mb, 1Gb, 2Gb and 4Gb). Test is passing.
> [cache_to_dmc] add dram size selection capability

- bsg_dataflow/bsg_sbox_ctrl_concentrate.v
- bsg_dataflow/bsg_stable_sort.v
- bsg_mem/bsg_cam_1r1w.v
- bsg_misc/bsg_mul_pipelined.v
1) bsg_sbox_ctrl_concentrate.v (issue #171): filename/module name consistency fix, submodule bsg_sort -> bsg_stable_sort
2) bsg_stable_sort.v (issue #170): filename/module name consistency fix
3) bsg_cam_1r1w.v (issue #184): empty_v_o double assignment fix
4) bsg_mul_pipelined.v (issue #179): all instances of clock_i have been renamed to clk_i to be consistent with the bsg format
> bug fixes for issues 170, 171, 179, 184

- bsg_mem/bsg_mem_1rw_sync_mask_write_byte_synth.v
if latch_last_read_p=1, last read value is latch at the output. When there is byte-masked write, it reads the bytes that are not masked, therefore destroying the last read value.
> fix the bug with reading mem when w_i=1, but write_mask_i[i]=0

- bsg_test/bsg_nonsynth_ramulator_hbm.v
- bsg_test/bsg_ramulator_hbm.cpp
* fixes a bug in the address translation from Ramulator addresses to channel addresses.
* adds a header guard in C++ file (needed to compile for cosimulation).
> Ramulator fixups

- bsg_noc/bsg_noc_repeater_node.v
Refactor brought in an obvious bug.  Accidentally was loopback instead of A<->B
> Fixing bug in repeater node

- bsg_mem/bsg_mem_3r1w.v
- bsg_mem/bsg_mem_3r1w_sync.v
- bsg_mem/bsg_mem_3r1w_sync_synth.v
- bsg_mem/bsg_mem_3r1w_synth.v
- hard/gf_14/bsg_mem/bsg_mem_3r1w_sync.v
Untested, but I was playing around with FPU integration in BP and that requires 3r1w memories for the FP regfile.  They need to be 3r1w to support high throughput FMA
> Add 3r1w mem

- bsg_cache/bsg_cache_sbuf.v
There's an incomplete assignment in bsg_cache_sbuf
> Removing implicit latch from store buffer

- hard/saed_90/bsg_mem/bsg_mem_1rw_sync.v
Fix1: added latch_last_read_p parameter in hardened bsg_mem_1rw_sync.v for RTL simulation
Fix2: hid bsg_clkgate_optional so that it does not cause any synthesis warning/error
> Ee525 module2 harden mem 1rw sync fix

- bsg_misc/bsg_circular_ptr.v
The bsg_circular_ptr module when simulated in VCS versions L-2016.06-SP2-15, O-2018.09-SP2-6, and P-2019.06 is not working correctly when slots_p is a non-power of 2. Specifically, it appeared as if statements in the combinational block with "+ add_i" was simply not being added. I am unclear about why this is showing up now ...
Logically, this module is the same after the fixes. I just changed the syntax which seems to work better with VCS.
Post synthesis results show a 0% change in area and 0% change in critical path for every path group.
> BSG Circular Pointer Non-pow2 Behavior Fix in RTL Simulation

- bsg_cache/bsg_cache_to_axi.v
- bsg_cache/bsg_cache_to_axi_rx.v
- bsg_cache/bsg_cache_to_axi_tx.v
Currently cache_to_axi assumes one bsg_cache attach to one cache_dma port, each bsg_cache has only one outstanding request. If more than one outstanding requests appear, tag_fifo would drop them.
This PR adds two features:
1. tag_fifo now has flow control, which stalls instead of dropping tags
2. tag_fifo size is parameterized and exposed to outside
> Cache_to_axi support multiple outstanding requests

- bsg_test/bsg_dramsim3_pkg.v
- testing/bsg_test/bsg_nonsynth_dramsim3/Makefile
- testing/bsg_test/bsg_nonsynth_dramsim3/testbench.v
adds helper structures for DRAM hierarchy address mapping.
> Dramsim3 address mapping

- bsg_test/bsg_trace_replay.v
Continued from PR #263 
Moved changes to bsg_test/bsg_trace_replay.v. Addressed the feedback by having multiple debug levels with comments about what level does what. More explicit begin-end to remove scope ambiguity.
> Adding debug_p parameter to control how verbose the display messages are.

- hard/gf_14/README.md
- hard/gf_14/bsg_clk_gen/bsg_clk_gen_osc.v
- hard/gf_14/bsg_misc/bsg_mux.v
In our cad flow, we currently search specifically for instances called BSG_BAL41MUX and set a don't touch attribute on those instances. I would like to generalize this such that any instance with *DONT_TOUCH* in the name gets the dont_touch attribute (similar to how we do things with *NO_CLOCK_GATE*.
> Change instance name to include the string DONT_TOUCH

- bsg_link/bsg_link_ddr_downstream.v
- bsg_link/bsg_link_ddr_upstream.v
Clarify that bsg_link_upstream and bsg_link_downstream need to be mirrored on source chip and destination chip. It is not a must to "pair" upstream and downstream on same chip.
> Update BSG Link Comments

- bsg_test/bsg_nonsynth_dramsim3.v
* A variable had both blocking and non-blocking assignments
* A return value was ignored
> Fixed two verilator errors for DramSim3

- bsg_misc/bsg_arb_fixed.v
- bsg_misc/bsg_encode_one_hot.v
- bsg_misc/bsg_id_pool.v
- bsg_misc/bsg_priority_encode.v
- bsg_misc/bsg_priority_encode_one_hot_out.v
The recursive nature of bsg_encode_one_hot leads to huge delays on the v_o signal for this module.  For a 16-entry priority encoder, I've seen 10-15 FO4 on the v_o port. I've squashed this path in the past by ignoring the v_o port and doing an OR on the bits outside of the module, but it makes sense for this fix to live inside the module.
My theory as to why the QoR is so bad is due to a lack of flattening.  Otherwise, I would think an OR reduce should synthesize fine, recursive or not
> Fixing critical path in bsg_encode_one_hot

- bsg_test/bsg_nonsynth_dpi_cycle_counter.hpp
- bsg_test/bsg_nonsynth_dpi_cycle_counter.v
On DPI-based stacks it is useful to have a cycle counter that can be read via DPI. This module and C++ class provide that functionality.
For example, in the Manycore Verilator simulation we need this to understand how long a program takes to execute.
> Added DPI-accessible cycle counter

- bsg_mem/bsg_nonsynth_mem_1rw_sync_assoc.v
Not quite infinite, but 63 bit (signed address) associative array is supported in verilator.
Need to make sure this fails well for X (X is an invalid index in a non-wildcard associative array)
> [WIP] Making associative memory verilator compatible

- bsg_test/bsg_nonsynth_dramsim3.v
Since the `bsg_nonsynth_dramsim3` module uses a synchronous memory for storing the data, we only need to shift the valid and address signals by one cycle in order to align them with the output data.
Also fixes the fails in `random_full` and `constrained_random` test suites in the `dramsim3_bandwidth` testbench.
> Fixed the signal alignment on dramsim3's read port

- bsg_test/bsg_nonsynth_dramsim3.v
- testing/bsg_test/bsg_nonsynth_dramsim3/Makefile
- testing/bsg_test/dramsim3_bandwidth/Makefile
- testing/bsg_test/dramsim3_bandwidth2/Makefile
This PR adds a byte masked version of the nonsynth DRAMSim3 module.
> Adding write mask to the DRAMSim3 module

- testing/bsg_dataflow/bsg_fifo_1r1w_small_hardened/filelist
- testing/bsg_noc/bsg_wormhole_concentrator/filelist
- testing/bsg_noc/bsg_wormhole_network/filelist
- testing/bsg_noc/bsg_wormhole_router/filelist
Resolve undefined macro problem in testbenches, so that they can run without error.
Keep filelists up-to-date.
> Update noc testbench filelist

- bsg_test/bsg_trace_replay.v
Missing case statement leads to ```### bsg_trace_replay UNKNOWN op 0 (testbench.trace_replay)``` for nops and terminates the simulation.  Credit to @gaozihou for the debug!
> Prevent erroring on trace-replay nop

- bsg_dmc/bsg_dmc_controller.v
If these counters that are used to enforce the minimum timing delays of the DRAM model overflow, it can add additional delays between issued DRAM operations.
> Fixing saturation of read and write counters in DRAM controller

- bsg_test/bsg_dramsim3.cpp
- bsg_test/bsg_dramsim3_pkg.v
- bsg_test/bsg_nonsynth_dramsim3.v
- bsg_test/bsg_nonsynth_dramsim3_map.v
- bsg_test/bsg_nonsynth_dramsim3_unmap.v
- testing/bsg_test/bsg_nonsynth_dramsim3/testbench.v
- testing/bsg_test/dramsim3_bandwidth/testbench.v
- testing/bsg_test/dramsim3_bandwidth2/testbench.v
- Added the `rochrababgco` address mapping to the translation modules
- Fixed a small error in Verilog parameter validation vs DRAMSim3
> Added new address mapping to DRAMSim3

- bsg_misc/bsg_defines.v
- bsg_misc/bsg_lru_pseudo_tree_backup.v
- bsg_misc/bsg_lru_pseudo_tree_decode.v
- bsg_misc/bsg_lru_pseudo_tree_encode.v
This PR adds a new macro to bsg_defines called BSG_SAFE_MINUS. This macro can be used to handle corner cases where widths tend to become negative (Although this is allowed in SV it might not be desirable). 
This macro is used in the Pseudo-LRU modules to handle the case where the number of ways = 1 (i.e direct-mapped)
> BSG_SAFE_MINUS

- bsg_mem/bsg_mem_1r1w.v
- bsg_mem/bsg_mem_1r1w_sync.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_bit.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_bit_synth.v
- bsg_mem/bsg_mem_1r1w_sync_synth.v
- bsg_mem/bsg_mem_1r1w_synth.v
- bsg_mem/bsg_mem_1rw_sync.v
- bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
- bsg_mem/bsg_mem_1rw_sync_mask_write_bit_synth.v
- bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
- bsg_mem/bsg_mem_1rw_sync_mask_write_byte_synth.v
- bsg_mem/bsg_mem_1rw_sync_synth.v
- bsg_mem/bsg_mem_2r1w.v
- bsg_mem/bsg_mem_2r1w_sync.v
- bsg_mem/bsg_mem_2r1w_sync_synth.v
- bsg_mem/bsg_mem_2r1w_synth.v
- bsg_mem/bsg_mem_3r1w.v
- bsg_mem/bsg_mem_3r1w_sync.v
- bsg_mem/bsg_mem_3r1w_sync_synth.v
- bsg_mem/bsg_mem_3r1w_synth.v
- bsg_misc/bsg_defines.v
- bsg_misc/bsg_lru_pseudo_tree_backup.v
- bsg_misc/bsg_lru_pseudo_tree_decode.v
- bsg_misc/bsg_lru_pseudo_tree_encode.v
This PR adds the BSG_SAFE_MINUS macro and supersedes #352 
The macro is used to allow for supporting a niche direct-mapped config in caches that are primarily set associative and hence have the LRU modules (effectively, this means "disabling" the LRU modules when used in a direct-mapped cache).
The macro is also used to support zero-width memories. One use case of zero width memories is the instantiation of a zero-width stat mem for a direct-mapped instruction cache.
I might have either added support to memories where it might not be used (i.e 2r1w or 3r1w?) or left out memories where it did not make sense to me to support zero width i.e (*_sync_mask_write_var?). Please do let me know if support should be removed/added for any of the memories modified in this PR.
> BSG SAFE MINUS and Zero Width Support for Memories

- bsg_misc/bsg_encode_one_hot.v
- bsg_misc/bsg_priority_encode_one_hot_out.v
This PR adds a fix to the priority encoder and its leaf modules to support width_p = 1.
> Fixing width_p = 1 for bsg_priority_encode

- hard/gf_14/bsg_mem/bsg_mem_1r1w_sync.v
- hard/gf_14/bsg_mem/bsg_mem_1r1w_sync_macros.vh
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync.v
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync_macros.vh
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync_mask_write_bit_macros.vh
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
- hard/gf_14/bsg_mem/bsg_mem_1rw_sync_mask_write_byte_macros.vh
- hard/gf_14/bsg_mem/bsg_mem_2r1w_sync.v
- hard/gf_14/bsg_mem/bsg_mem_2r1w_sync_macros.vh
- hard/gf_14/bsg_mem/bsg_mem_3r1w_sync.v
- hard/gf_14/bsg_mem/bsg_mem_3r1w_sync_macros.vh
This PR adds hooks to the hardened memories so that external designs can define their own macros without having to change the files here.  This has several advantages:
- Not having to maintain separate incompatible tapeout branches for each design
- Not all memories have an optimal configuration; this allows us to specialize per design
- Adds hooks for users who are straight compiling instead of using a "swap" methodology
> Adding gf12 macro defines for individual design memories

- bsg_dataflow/bsg_parallel_in_serial_out.v
- testing/bsg_dmc/filelist.lst
Current design requires that when v_i==1, value of data_i must hold until ready_and_o==1. This requirement may not always be fulfilled when attached to other BaseJump modules.
Updated design breaks the constraint by moving "extra buffering" from first word to last word, therefore data_i always enqueue into PISO within one cycle.
> PISO Break Unnecessary Constraint on v_i and data_i

- bsg_test/bsg_dramsim3_pkg.v
This is a scoping issue that I believe is technically undefined behavior in the LRM, since the enum is potentially undefined at elaboration unless it happens to elaborate in the correct order. Adding the type allows it to compile with latest Verilator.
> Adding type definition for bsg_dramsim3_pkg

- bsg_misc/bsg_scan.v
genvar j is declared above; no need to redeclare it.
Causing warning in Verilator
> Removing shadowed genvar

- bsg_dataflow/bsg_parallel_in_serial_out_passthrough.v
- bsg_noc/bsg_wormhole_stream_in.v
- bsg_noc/bsg_wormhole_stream_out.v
This change modifies the wormhole streamer modules to use passthrough_dynamic variants of SIPO/PISO when protocol data width < link flit width. The streamer protocol client provides an expected number of data flits and then the wormhole streamer computes the number of protocol data flits per PISO/SIPO transaction.
Without this feature, the protocol client would need to send extra null data packets (SIPO) or drain null data packets (PISO) to completely fill or drain the SIPO/PISO, respectively.
~~This change allows the wormhole_stream_out module to drain invalid client data flits. This can occur when the input link flit width is greater than the output client protocol data width, if the client protocol message does not have a full link flit width of data. Without the drain, the client …
> Fix wormhole streamers to use passthrough_dynamic SIPO/PISO

- bsg_misc/bsg_circular_ptr.v
When switching to VCS 2020, from VCS 2019 this assertion starts to fire. Whatever causes it does not seem to change the correctness, but it does cause error messages.
`assert final`, which waits until signals have stabilized, fixes the problem
Happy to add comments, etc.
> Switch to assert final for bsg_circular_ptr, to satisfy VCS 2020

- bsg_test/bsg_nonsynth_reset_gen.v
Switched input and output of nonsynth_reset_gen to bit (instead of logic)
In newer versions of VCS, casting between logic and bit types triggers new positive/negative edges at T=0 when 'x' -> '1/0'. 
To solve this (and be backward compatible) this PR changes the type of `clk_i` and `async_reset_o` to bit so that users can use bits in the instantiating module and avoid negative/positive edges, or use logic and maintain the old behavior.
Replaces #376
> Switch bsg_nonsynth_reset_gen input/output to bit instead of (implicit) logic to spurious pos/neg edges at T=0

- bsg_test/bsg_nonsynth_dpi_from_fifo.v
- bsg_test/bsg_nonsynth_dpi_to_fifo.v
In LRM, `generate if` takes `constant_expression`, but `inside` is `expression`.
So `inside` can't be used in `generate if`.
> LRM A.4.2
> if_generate_construct ::=
if ( constant_expression ) generate_block [ else generate_block ]
> Remove inside in generate if

- bsg_test/bsg_dramsim3.vh
- bsg_test/bsg_dramsim3_pkg.v
> DRAMSim3 moves macros from source to header

- bsg_dataflow/bsg_fifo_reorder.v
This change lets us associate the dequeued data with some external data storage, which may be written at a different time than the fifo data
> Adding deq id to reorder fifo

- bsg_cache/bsg_cache.v
Currently using a logical expression to derive the amo support level causes the parameter to infer that it is a 1-bit variable. This patch guarantees that it remains 32-bits no matter what is passed in
> Explicitly size amo_support_p in bsg_cache

- bsg_test/bsg_dramsim3.cpp
- bsg_test/bsg_nonsynth_dramsim3.v
Part of changes for stat tag support for DRAMSim3
https://github.com/bespoke-silicon-group/bsg_replicant/commit/0f0525a543a948f62aafa3261d1e115fb376006e 
https://github.com/bsg-external/DRAMsim3/commit/c560aa2158dd825d415db63af967c1d347c28663
> Added support to call DRAMSim3 StatsPrint with stats_snoop

- bsg_misc/bsg_expand_bitmask.v
This PR supports expand_p = 0 in `bsg_misc/bsg_expand_bitmask` by making them passthrough.
> Supporting expand_p = 0 in BSG_EXPAND_BITMASK

- bsg_test/bsg_nonsynth_dpi_clock_gen.cpp
- testing/bsg_test/bsg_nonsynth_dpi/top.v
* Swapped the order of pop and push - using a reference when poping will automatically update the reference.
Sort of fixes #421
> Fixed bug in DPI Clock Generator

- hard/gf_14/README.md
- hard/gf_14/bsg_clk_gen/bsg_clk_gen_osc.v
- hard/gf_14/bsg_misc/bsg_mux.v
Changing the special DONT_TOUCH instance names to BSG_DONT_TOUCH to be more consistent with other special variables in our cad flows. This also makes it more clear that this is a BSG feature and not something that EDA tools support by default.
The change of NO_CLOCK_GATE to BSG_NO_CLOCK_GATE is just a documentation error. The flow and RTL already uses BSG_NO_CLOCK_GATE.
> Changing the special DONT_TOUCH instance names to BSG_DONT_TOUCH

- bsg_misc/bsg_defines.v
This + https://github.com/verilator/verilator/pull/3026 fixes #446 and allows verilator to work with BSG_ABSTRACT_MODULE construct
> Adding pinmissing lint exception for BSG_ABSTRACT_MODULE

- bsg_tag/bsg_tag_client.v
This will of course require some patches to various modules, but it should be straight-forward delete of the default parameter and the reset input signal; I believe no current hardware makes us of the reset signal; it was essentially a fail-safe (what happens if tag client does not work!) that was too complicated to use in practice.
> remove reset from bsg_tag_client

- bsg_misc/bsg_defines.v
To fix dumb vivado behavior on code e.g.
```
~mideleg_lo[0+:$bits(exception_dec_li)] & $bits(exception_dec_li)'($signed(mgie))
```
> Add BSG_SEXT and BSG_ZEXT

- bsg_test/bsg_nonsynth_dpi_gpio.v
Fixes a syntax error introduced during a refactor of the invalid parameter settings.
I don't have merge perms on this repo, so to whoever approves this, can you please merge it immediately? Thank you.
> fixes syntax error

- bsg_test/bsg_nonsynth_dpi_gpio.hpp
https://www.amiq.com/consulting/2019/01/30/how-to-call-c-functions-from-systemverilog-using-dpi-c/
> Safer datatype conversion for DPI GPIO

- bsg_cache/bsg_cache_to_axi.v
- bsg_cache/bsg_cache_to_axi_rx.v
- bsg_cache/bsg_cache_to_axi_tx.v
Currently, we embed the hash function from multiple caches to AXI channels inside the module. This is not flexible enough to handle multiple schemes, which might correspond to different topologies, striping schemes or different ratios of caches to channels. This PR separates out the raw AXI addresses and cache tags, so that a user can implement their own hash function after the AXI conversion.
Usage seen here: https://github.com/black-parrot/black-parrot/commit/be10baeb7565b4576262b73ed6f1439e42567bc3
> Separating out addr and tag in bsg_cache_to_axi

- bsg_misc/bsg_dlatch.v
- bsg_misc/bsg_latch.v
Verilator 4.213 does not recognize assignments to outputs as a latch. The proposed patch should have no inference change on synthesis
> Fixing latch for verilator

- bsg_misc/bsg_defines.v
Verilator doesn't like the module name (foobar_abstract) mismatching the file name (foobar.v), this waiver lets it be ignored without disabling the check overall.
> Adding declfilename waiver to bsg_defines

- bsg_cache/bsg_cache_non_blocking.v
- bsg_cache/bsg_cache_non_blocking.vh
- bsg_cache/bsg_cache_non_blocking_data_mem.v
- bsg_cache/bsg_cache_non_blocking_decode.v
- bsg_cache/bsg_cache_non_blocking_dma.v
- bsg_cache/bsg_cache_non_blocking_mhu.v
- bsg_cache/bsg_cache_non_blocking_miss_fifo.v
- bsg_cache/bsg_cache_non_blocking_pkg.v
- bsg_cache/bsg_cache_non_blocking_stat_mem.v
- bsg_cache/bsg_cache_non_blocking_tag_mem.v
- bsg_cache/bsg_cache_non_blocking_tl_stage.v
- bsg_cache/bsg_cache_to_dram_ctrl.v
- bsg_dmc/bsg_dmc.v
- bsg_dmc/bsg_dmc.vh
- bsg_dmc/bsg_dmc_controller.v
- bsg_dmc/bsg_dmc_pkg.v
- bsg_noc/bsg_mesh_router_decoder_dor.v
- testing/bsg_cache/common/bsg_nonsynth_non_blocking_dma_model.v
- testing/bsg_cache/dmc/testbench.v
- testing/bsg_cache/regression_non_blocking/basic_checker.v
- testing/bsg_cache/regression_non_blocking/block_ld_checker.v
- testing/bsg_cache/regression_non_blocking/cov_mhu.v
- testing/bsg_cache/regression_non_blocking/cov_miss_fifo.v
- testing/bsg_cache/regression_non_blocking/cov_tl_stage.v
- testing/bsg_cache/regression_non_blocking/tag_checker.v
- testing/bsg_cache/regression_non_blocking/testbench.v
- testing/bsg_dmc/testbench.v
In order for some tools to handle basejump code, each file needs to be able to parse as its own compilation unit. This means we can't rely on definitions from packages being available at import time.  This PR separates out bsg_cache_non_blocking_pkg and bsg_dmc_pkg defines into their own include files. Users should both import the package and include the defines
> Removing defines from bsg_cache_non_blocking_pkg and bsg_dmc_pkg

- bsg_link/bsg_link_pkg.v
This PR adds a tag package for SDR links. This helps standardize the chip interface for these modules, as these offsets can be included in other projects, etc.
> Sdr tag pkg

- bsg_noc/bsg_wormhole_concentrator_in.v
- bsg_noc/bsg_wormhole_concentrator_out.v
This PR fixes the width of constants used to stub the data wires of stubbed links in the wormhole concentrators. Functionality of modules is unchanged.
> fix data width assignment of stubbed links in wh concentrators

- bsg_noc/bsg_wormhole_concentrator.v
- bsg_noc/bsg_wormhole_concentrator_in.v
- bsg_noc/bsg_wormhole_concentrator_out.v
- bsg_noc/bsg_wormhole_router.v
- bsg_noc/bsg_wormhole_router_output_control.v
This PR simply exposes the hold_on_valid_p parameter from bsg_round_robin_arb.v in bsg_wormhole_router_output_control, bsg_wormhole_router, and bsg_wormhole_concentrator*.
This parameter is useful in situations where an output channel may not be consumed in a single cycle, for example when a flit must be processed by a PISO.
> expose hold_on_valid_p param in wh router and concentrators

- bsg_dataflow/bsg_fifo_1r1w_small_credit_on_input.v
This PR allows us to harden credit fifos in addition to regular 1r1w small fifos
> Add harden param to credit fifo

- bsg_clk_gen/bsg_clk_gen_osc.v
- bsg_clk_gen/bsg_dly_line.v
- bsg_test/bsg_nonsynth_clock_gen.v
This PR adds the capability to tune our nonsynth oscillators (clock gen and delay line), for different process nodes using BSG_OSC_BASE_DELAY and BSG_OSC_GRANULARITY. By setting these parameters, we can get a fairly good approximation of the delays after APR. This is especially useful / necessary for the DMC which relies on relative delays between the oscillators and interface.
It also adds the BSG_NO_TIMESCALE macro which removes timescale from all modules. This is useful for simulating with libraries which have a defined timescale, since there are very messy semantics for overriding timescale in SystemVerilog.
> Updates to clock gen osc and delay line

- bsg_mem/bsg_mem_1r1w.v
- bsg_mem/bsg_mem_1r1w_sync.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_bit.v
- bsg_mem/bsg_mem_1r1w_sync_mask_write_bit_synth.v
- bsg_mem/bsg_mem_1r1w_sync_synth.v
- bsg_mem/bsg_mem_1r1w_synth.v
- bsg_mem/bsg_mem_1rw_sync_banked.v
- bsg_mem/bsg_mem_2r1w_sync.v
- bsg_mem/bsg_mem_2r1w_sync_synth.v
- bsg_mem/bsg_mem_3r1w_sync.v
- bsg_mem/bsg_mem_3r1w_sync_synth.v
- hard/common/bsg_mem/bsg_mem_generator.py
Some of our synth memories have parameters for harden_p, some do not. It doesn't really make sense to have in an explicitly synth block, so this PR removes the parameter. None of our code instantiates synth memories directly so no additional updates should be needed. It also updates bsg_mem_generator to reflect this
> Unharden synth memories

- bsg_cache/bsg_cache.v
- bsg_cache/bsg_cache.vh
- bsg_cache/bsg_cache_dma_to_wormhole.v
- bsg_cache/bsg_cache_miss.v
- bsg_cache/bsg_cache_pkg.v
- bsg_cache/bsg_cache_to_test_dram.v
- bsg_cache/bsg_cache_to_test_dram_tx.v
- bsg_cache/bsg_wormhole_to_cache_dma_fanout.v
- Adding read, masked write, and non-masked write to the cache dma wormhole packet.
- Updating cache wormhole and  test_dram related modules.
- Making change in miss handling logic to treat SM with all the mask bits as 1'b1 like SW.
> bsg_cache_word_tracking wormhole change

- bsg_async/bsg_async_fifo.v
This PR fixes an apparent problem with the async fifo when is connected to a module which unconditionally latches the output data (without considering the valid).
```
We're seeing a timing violation by connecting an async fifo to bsg_serial_in_parallel_out:
https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_async/bsg_async_fifo.v
https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_dataflow/bsg_serial_in_parallel_out.v
What's happening is the async fifo memory is getting updated with the write clock. Then, the data is asynchronously read by the reader. Note: the rvalid is low at this point, as expected. However, the bsg_serial_in_parallel_out updates its data every cycle, regardless of valid. Therefore, the data gets corrupted. It doesn't affect …
```
> Async fifo with cleaner CDC

- testing/bsg_noc/bsg_wormhole_concentrator/Makefile
- testing/bsg_noc/bsg_wormhole_concentrator/bsg_wormhole_concentrator_tester.v
- testing/bsg_noc/bsg_wormhole_router/Makefile
- testing/bsg_noc/bsg_wormhole_router/bsg_wormhole_router_tester.v
This PR updates testbenches for wormhole router and concentrator. Now it supports hold_on_valid_p verification.
> Update wormhole router and concentrator testbench

- hard/tsmc_28/bsg_mem/bsg_mem_1r1w_sync_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_1r1w_sync_mask_write_bit_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_1r1w_sync_mask_write_byte_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_1rw_sync_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_1rw_sync_mask_write_bit_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_1rw_sync_mask_write_byte_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_2r1w_sync_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_2rw_sync_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_2rw_sync_mask_write_bit_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_2rw_sync_mask_write_byte_macros.vh
- hard/tsmc_28/bsg_mem/bsg_mem_3r1w_sync_macros.vh
Adds memory macros for TSMC28. Part of a decomposition of #492
> Adding memory macros for TSMC 28

- bsg_test/bsg_nonsynth_axi_mem.v
This PR fixes two latch warnings and a blocking assign in sequential logic present in the bsg_nonsynth_axi_mem module, discovered during zynq-parrot compilation with Verilator.
> fix latch warnings and seq logic assign in nonsynth_axi_mem

- bsg_misc/bsg_crossbar_control_locking_o_by_i.v
This PR adds a locking crossbar, which is useful for crossbars which have multiple beat streams and no tag info on their data payloads
> Adding bsg_crossbar_control_locking_o_by_i.v

- testing/bsg_dmc/testbench.v
Hi!
Some commercial tool complains about packed dimensions not specifying a range. Please double check that the widths are correct before merging!
Thanks!
Flavien
> Add range to packed arrays

- testing/bsg_dmc/lpddr_verilog_model/mobile_ddr_mcp.v
Maybe replace comments with ifdefs, as looks the best for you.
Thanks!
Flavien
> Make mobile_ddr_mcp usable out of the box

- bsg_dataflow/bsg_round_robin_fifo_to_fifo.v
This include is needed in this file, for instance for defining `BSG_INV_PARAM`.
> Uncomment include bsg_defines

- bsg_cache/bsg_cache_to_test_dram_rx.v
- bsg_cache/bsg_cache_to_test_dram_rx_reorder.v
- testing/bsg_cache/common/basic_checker_32.v
- testing/bsg_cache/regression_64/basic_checker.v
- testing/bsg_cache/regression_non_blocking/ainv_checker.v
- testing/bsg_cache/regression_non_blocking/basic_checker.v
- testing/bsg_cache/regression_non_blocking/block_ld_checker.v
- testing/bsg_cache/regression_non_blocking/tag_checker.v
- testing/bsg_dataflow/bsg_fifo_reorder/testbench.v
- testing/bsg_misc/bsg_lru_pseudo_tree_backup/testbench.v
- testing/bsg_misc/bsg_lru_pseudo_tree_encode/testbench.v
- testing/bsg_test/dramsim3_bandwidth/testbench.v
Hi there!
The fatal syntax here was incorrect and made the Morty tool unhappy (cf. [this issue](https://github.com/pulp-platform/morty/issues/46)). This should fix it.
> Fix fatal syntax

- bsg_cache/bsg_cache_dma.v
- testing/bsg_cache/regression_v2/Makefile
- testing/bsg_cache/regression_v2/test_store_random1.py
- testing/bsg_cache/regression_v2/testbench.v
- basically, when word_tracking_p = 0, track_data_we_i will always be zero in bsg_cache_dma. This means that track_mem_data_r will always be 'X.  Then data_mem_v_o will also become X, and so will tl_ready at the top.
- added word_tracking_p switch to regression_v2
- Added asserting to check if ready_o or v_o ever goes X in testbench, because the testbench didn't fail even when there was x.
> [bsg_cache] fix track_mem_data_r X when word_tracking_p = 0

- bsg_misc/bsg_defines.v
- bsg_test/bsg_nonsynth_clock_gen.v
This also includes some help macros to bsg_defines.v to do some logical and and logical or operations to defined macros.
> Adding Verilator Timing Check to bsg_nonsynth_clock_gen

- bsg_misc/bsg_idiv_iterative.v
- Fixed undeclared signals: add_in0, add_in1.
- Fixed add2_out being 'Z, when bits_per_iter_p=1. It was fixed, because the top bit goes into idiv controller, and it's being flopped there.
> [idiv] fix some undeclared and unassigned signals

- bsg_test/bsg_nonsynth_axi_mem.v
Adding nonsynth AXI memory from: https://github.com/black-parrot-hdk/zynq-parrot/pull/36.
The previous behavior is supported by passing a constant burst length into arlen/awlen. This is a nonsynth module so there are no PPA implications
> Adding burst length input to nonsynth axi mem

- testing/Makefile.sim
- testing/bsg_dataflow/Makefile
- testing/bsg_dataflow/bsg_channel_narrow/Makefile
- testing/bsg_dataflow/bsg_channel_narrow/test_bsg.v
- testing/bsg_dataflow/bsg_channel_tunnel/Makefile
- testing/bsg_dataflow/bsg_channel_tunnel/test_bsg.v
- testing/bsg_dataflow/bsg_compare_and_swap/Makefile
- testing/bsg_dataflow/bsg_compare_and_swap/test_bsg.v
- testing/bsg_dataflow/bsg_fifo_1r1w_large/Makefile
- testing/bsg_dataflow/bsg_fifo_1r1w_large/test_bsg_fifo_1r1w_large.v
- testing/bsg_dataflow/bsg_fifo_1r1w_pseudo_large/Makefile
- testing/bsg_dataflow/bsg_fifo_1r1w_pseudo_large/test_bsg_fifo_1r1w_pseudo_large.v
- testing/bsg_dataflow/bsg_fifo_bypass/Makefile
- testing/bsg_dataflow/bsg_fifo_bypass/sv.include
- testing/bsg_dataflow/bsg_fifo_reorder/Makefile
- testing/bsg_dataflow/bsg_parallel_in_serial_out/Makefile
- testing/bsg_dataflow/bsg_parallel_in_serial_out_passthrough_arb/sv.include
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/sv.include
- testing/bsg_dataflow/bsg_serial_in_parallel_out_passthrough/testbench.v
Refactored testbench infrastructure update from https://github.com/bespoke-silicon-group/basejump_stl/pull/610
Fixes testbenches and makefiles (allows them to compile and run) for all existing dataflow tests.
Adds `bsg_dataflow` level makefile to run all make commands in directory (for easy syntax verification and directory-level clean commands)
Previous infrastructure had not been updated in a number of years, leading to issues regarding compilation from updated module port lists and outdated tooling/non-automated tooling setup in Makefiles
I have verified that all testbenches are properly run via using `make` on each subdirectory in `testing/bsg_dataflow`
`bsg_fifo_1r1w_large` and `bsg_fifo_1r1w_large` do not properly finish as they have log file errors I do not understand but the tests …
> Updates testbenches for bsg_dataflow

- bsg_misc/bsg_defines.v
We could add this flag in preparation for -DSURELOG, or wait for it to be added upstream. Won't break anything in the meantime so I'd suggest merging early.
> Adding SURELOG to list of synthesis tools

- bsg_noc/bsg_noc_pkg.sv
header guards are not recommended on packages because they can cause compilation ordering issues
> Update bsg_noc_pkg.v to remove `ifdef

- bsg_dataflow/bsg_fifo_bypass.sv
> bsg_dataflow/bsg_fifo_bypass.sv: Fix incorrect port name

- bsg_dmc/bsg_dmc_dly_line_v3.sv
Add a missing include to bsg_dmc/bsg_dmc_dly_line_v3.sv. Without this line we get errors when trying to run simulation since the file uses some of the macros defined in bsg_misc/bsg_defines.sv.
> bsg_dmc/bsg_dmc_dly_line_v3.sv: Fix missing include

- bsg_mem/bsg_mem_1rw_sync_mask_write_bit_from_1r1w.sv
Reorder variable declarations so that addr_li is not referenced before its declaration. Fixes #674
> bsg_mem/bsg_mem_1rw_sync_mask_write_bit_from_1r1w.sv: Fix variable order

- bsg_misc/bsg_defines.sv
YOSYS is not Vivado, so we should identify it as such
> Update bsg_defines.sv for yosys

- hard/ultrascale_plus/bsg_mem/bsg_mem_1r1w_sync.sv
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync.sv
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.sv
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.sv
This PR adds xilinx templates for BRAM inference. This is essential for efficient implementation on FPGA. 
TODO: Designate between BRAM and URAM inference for a given width and depth. Currently trusting xilinx
Tested with BP on Vivado 2022.1, correctly infers all 1rw_sync* and 1r1w_sync* RAMs
> Harden Xilinx memories

- bsg_mem/bsg_mem_1rw_sync_mask_write_byte_synth.v
- hard/ultrascale_plus/bsg_mem/bsg_mem_1r1w_sync_mask_write_byte.v
- hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
Original code causes inefficient block ram mapping with Xilinx Ultrascale FPGAs, since every byte is mapped to a separate RAMB18E2 (50% utilization in the best case).
This PR hardens the byte masking block ram for Ultrascale Plus FPGAs. With this change, byte make BRAM utilization will reduce at least by half.
Reference: Vivado Design Suite User Guide: Synthesis (UG901), Byte Write Enable (Block RAM), https://docs.xilinx.com/v/u/2019.1-English/ug901-vivado-synthesis
> [WIP] Ultrascale plus byte mask block ram

- bsg_link/bsg_link_isdr_phy.sv
- bsg_link/bsg_link_osdr_phy.sv
- bsg_link/bsg_link_sdr_downstream.sv
- bsg_link/bsg_link_sdr_upstream.sv
- hard/gf_14/bsg_link/bsg_link_isdr_phy.sv
- hard/gf_14/bsg_link/bsg_link_osdr_phy.sv
- hard/gf_14/bsg_link/tcl/bsg_link_ddr.constraints.tcl
- hard/gf_14/bsg_link/tcl/bsg_link_sdr.constraints.tcl
- hard/tsmc_28/bsg_link/bsg_link_isdr_phy.sv
- hard/tsmc_28/bsg_link/bsg_link_osdr_phy.sv
- hard/tsmc_28/bsg_link/tcl/bsg_link_sdr.constraints.tcl
Add token boundary cells to improve token clock driving strength
Update token clock timing constraints, add token clock driving cell
> SDR Token Clock Timing

- bsg_misc/bsg_defines.sv
Disables unnamed genblk warning in Verilator, VCS and Xcelium
> Naming abstract gen block

- hard/gf_14/bsg_clk_gen/bsg_rp_clk_gen_atomic_delay_tuner.sv
- hard/gf_14/bsg_clk_gen/bsg_rp_clk_gen_coarse_delay_tuner.sv
- hard/gf_14/bsg_clk_gen/bsg_rp_clk_gen_fine_delay_tuner.sv
These files are netlist files (not hard swap files) and are read by synthesis using a different engine than typical RTL files. This engine does not support macros with arguments therefore this macro can not be part of a netlist files.
> Removing BSG_ABSTRACT_MODULE from gf14 clk gen netlist modules

- testing/Makefile.sim
Small changes to enable Verilator as an option in Makefile.sim, checked with `Verilator 5.034 2025-02-24 rev v5.034-47-gac3f30ed6`. Included guards for `define in various test_bsg.sv files since Verilator and VCS have different behaviors when trying to override macro definitions using +define+ in the command line.
> Add Verilator support to Makefile.sim
